### PR TITLE
Invalidate jquery module cache upon refresh.

### PR DESCRIPTION
**Pull request by yinso**
Based on #38 - added jquery as a module to be unloaded.

### CODE REVIEW

**Comment by jaruba** [comment]
Thanks! :)

**Comment by yinso** [comment]
No problem, thanks ;)

**Comment by jaruba** [comment]
oh, i just realized there was an error in your code, you're missing a quote, might fixing it?
https://github.com/yinso/wcjs-player/commit/5f6fec3a11d7d5de16659cdfeb0e80a5fa9625d9#diff-168726dbe96b3ce427e7fedce31bb0bcR55

**Comment by yinso** [comment]
Weird, I actually ran it without issues... sorry about that, will update.

**Comment by yinso** [comment]
Ah - it turns out that I accidentally linked the code to a different directory I was also at, so I will have to look at this a bit more. Go ahead and revert if you want, will update... sorry.

**Pull request merged**
