### PR TITLE
FirstPlay event (issue #53)

### PR DESCRIPTION
**Pull request by Chayemor**
Access to 'firstPlay' event, triggered when a new item starts playing,
after the change to the aspect occurs. To use -->
player.onFirstPlay(function() {});

### CODE REVIEW

**Comment by Chayemor** [comment]
Is it accessible via "npm install wcjs-player" ?

**Comment by jaruba** [comment]
Yes, I published it right now.

**Comment by Chayemor** [comment]
I do appreciate it, thanks !

**Comment by jaruba** [comment]
No problem, this is how a project grows. :)

**Pull request merged**
